### ISSUE TITLE
Rucky Support

### ISSUE THREAD

**Issue by si4v45h** [FlopKernel-Series/flop_trinket-mi_kernel#2]
Rucky is an app which executes Rubber Ducky scripts and yes, the Net Hunter is already doing that in HID attack section as well, but it's just a cool idea if the Rucky app works too. it's not that emergency but it would be great if the kernel also supports it.

[Here's the app's GitHub page](https://github.com/mayankmetha/Rucky/)
[The NetHunter Store link](https://store.nethunter.com/en/packages/com.mayank.rucky/)
take a look at the pictures I attached down below:

![Rucky Kernel Support Error](https://user-images.githubusercontent.com/128404354/231039183-943fa515-b064-4ec4-a95a-557576c3442c.png)

![Rucky Logo](https://user-images.githubusercontent.com/128404354/231039202-a82fafc5-b188-496c-ada3-848d9f9ddd87.png)

**Comment by Flopster101** [comment]
Can you perhaps check if it's working on MS9? ConfigFS should be enabled.

**Comment by si4v45h** [comment]
It's working flawlessly!

**Comment by si4v45h** [comment]
It's working flawlessly!
![IMG_20230626_171422](https://github.com/Flopster101/flop_ginkgo_kernel/assets/128404354/cd4e5720-5eaa-47e1-b51c-1106de3e239c)
To make it work , first we must enable HID in USB Arsenal section in Nethunter app , then get back to the rucky and run our desired script.
Great job and thank you for your work❤️
