### ISSUE TITLE
zstd 1.5.5

### ISSUE THREAD

**Issue by romanovj** [FlopKernel-Series/flop_trinket-mi_kernel#4]
you can use latest zstd from Facebook zstd GitHub repo

https://github.com/facebook/zstd

I compiled your kernel with this changes
[linux.zip](https://github.com/Flopster101/flop_ginkgo_kernel/files/11916423/linux.zip)

**Comment by romanovj** [comment]
in order to get sources for kernel you need to execute
cd zstd/contrib/linux-kernel
make

**Comment by Flopster101** [comment]
Thanks for the idea! I'll be testing this out for MS10

**Comment by Flopster101** [comment]
Upstream to v1.5.5 implemented as of commit 7865848a2916841d8207bc440f62c0acfb57b4fc.
