### ISSUE TITLE
[help] chinese variant slow charging

### ISSUE THREAD

**Issue by whyakari** [FlopKernel-Series/flop_trinket-mi_kernel#6]
Hi, looks like you fixed the slow loading on the Chinese variant. Could you explain or show me how I can apply this commit to my kernel too? (ginkgo here too)

**Comment by Flopster101** [comment]
Commit 0c9922331bbeac0df9663acef95bfbfdc2ae22cf should fix it. For good measure, maybe you want to pick 28d6c409752d0eabdfe9cbd3e3aa5db8e33a1b06 too.
