### ISSUE TITLE
Conflicts with Magisk

### ISSUE THREAD

**Issue by TheWrathRF** [FlopKernel-Series/flop_trinket-mi_kernel#9]
No matter flashing first kernel then magisk vice versa. Ramdisk state becomes to "No" in Magisk app and if you try to repatch boot image via Magisk app bootloop occurs as expected. Also the kernel does work on crdroid ( Magisk problem still occurs) but it does not work on PixelOS ( dynamic version used)

**Comment by Flopster101** [comment]
I can assure you that Carakernel (MS18 and MS17) does work on PixelOS (A14), as that's what I mainly test it on. I have not been able to replicate your issue so you should provide some logs first.

**Comment by TheWrathRF** [comment]
Okay I 'll provide some logs but it definitely conflicts with magisk. Have you tried that also?

**Comment by Flopster101** [comment]
Yes, I tried with Magisk for a while (before the final release) and it worked fine, I only stopped using it because how hard it is to make it pass device integrity.

**Comment by TheWrathRF** [comment]
Problem got solved. It was happening due to partition corruption on my side.

**Comment by Flopster101** [comment]
Okay, good to know 👍

**Comment by TheWrathRF** [comment]
It occured again. The kernel still causes ramdisk "no" issue. Here is the log 
[logcat--2024-06-22--13-04.log](https://github.com/user-attachments/files/15936272/logcat--2024-06-22--13-04.log)
